import type { Metadata } from "next";
import "./globals.css";
import { ThemeProvider } from "next-themes";
import Header from "@/components/Header";
import Footer from "@/components/Footer";
import AuthContextProvider from "@/context/AuthContext";
import TanstackProvider from "@/providers/TanstackProvider";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body>
        <TanstackProvider>
          <AuthContextProvider>
            <ThemeProvider attribute="class" defaultTheme="system" enableSystem>
              <Header />
              <main className="min-h-screen">{children}</main>
            </ThemeProvider>
            <Footer />
          </AuthContextProvider>
        </TanstackProvider>
      </body>
    </html>
  );
}
